"""AgenticCodingLoop on Temporal, generated by provenflow.

The control flow is the verified state machine of agentic_coding_loop_fsm.py (generate it from the same
diagram): each state only decides which event to fire, and the move is applied by the verified
machine, which rejects anything the model does not allow.
"""

from datetime import timedelta

from temporalio import activity, workflow

with workflow.unsafe.imports_passed_through():
    import agentic_coding_loop_fsm as m

#: States decided by a person through the human_event signal instead of the decide activity.
#: Guessed from the diagram (names, labels, attributes mentioning a human): adjust as needed.
HUMAN_STATES = ["prompting","designing","security_review1","quality_review1","rework_developing","security_review2","quality_review2","human_review","release_decision","on_hold"]


@activity.defn
async def decide(state: str, allowed: list, values: dict) -> str:
    """Decide which event to fire in `state`: call your LLM, tool or a human here.

    allowed: the events the verified model allows now (offer them to the LLM, e.g. as a tool enum).
    values: attribute and variable values of the current state.
    Returning an event outside `allowed` raises InvalidTransition.

    Activities may call LLMs and other non-deterministic services; the workflow stays deterministic."""
    raise NotImplementedError("decide(%r, %r): plug in your LLM / tool" % (state, allowed))


@workflow.defn
class AgenticCodingLoopWorkflow:
    def __init__(self) -> None:
        self._human_events: list = []
        self._fsm = None

    @workflow.signal
    def human_event(self, event: str) -> None:
        """A person's decision (e.g. approve / reject) for the current human state."""
        self._human_events.append(event)

    @workflow.query
    def current_state(self) -> str:
        return self._fsm.state.value if self._fsm else m.INITIAL_STATES[0].value

    @workflow.query
    def allowed_events(self) -> list:
        return [e.value for e in self._fsm.allowed_events()] if self._fsm else []

    @workflow.run
    async def run(self, max_steps: int = 1000) -> list:
        # Workflows are single-threaded and sandboxed: no lock around send().
        fsm = m.AgenticCodingLoopFSM(on_invalid="return", thread_safe=False)
        self._fsm = fsm
        for _ in range(max_steps):
            allowed = [e.value for e in fsm.allowed_events()]
            if not allowed:
                break
            if fsm.state.value in HUMAN_STATES:
                await workflow.wait_condition(lambda: bool(self._human_events))
                event = self._human_events.pop(0)
            else:
                event = await workflow.execute_activity(
                    decide, args=[fsm.state.value, allowed, fsm.values], start_to_close_timeout=timedelta(minutes=5)
                )
            fsm.send(event)  # rejected choices leave the state unchanged: decide again
        return [record["event"] for record in fsm.history]
