import { isBinaryExpression, isBooleanLiteral, isNameReference, isNumberLiteral, isStateVariable, isUnaryExpression, type Expression } from './generated/ast.js';
import type { DiagramModel } from './model.js';
import { parseDiagram } from './parse.js';
import { generatePython, transitionEvents, type GeneratedPython } from './python-generator.js';
import { serializeDiagram } from './serializer.js';

export type Framework = 'xstate' | 'langgraph' | 'burr' | 'temporal';

export const FRAMEWORKS: Array<{ id: Framework; label: string; extension: string; description: string }> = [
    { id: 'xstate', label: 'XState v5 (TypeScript)', extension: 'ts', description: 'setup().createMachine() with guards and assign actions; visualise it in Stately' },
    { id: 'langgraph', label: 'LangGraph (Python)', extension: 'py', description: 'StateGraph with a node per state; edges follow the verified transitions' },
    { id: 'burr', label: 'Burr (Python)', extension: 'py', description: 'ApplicationBuilder with an action per state and when(event=...) transitions' },
    { id: 'temporal', label: 'Temporal (Python)', extension: 'py', description: 'Durable workflow whose loop only takes verified transitions; LLM calls are activities' }
];

export interface FrameworkExport {
    fileName: string;
    code: string;
    /** Other files the export needs (the generated FSM module for the Python targets). */
    requires: string[];
}

/**
 * Exports the verified machine to an agent/workflow framework. The Python
 * targets wrap the generated <name>_fsm.py module, so the transition table,
 * guards and updates stay the verified ones; each state only has to decide
 * which event to fire (your LLM, tool or human), and illegal choices are rejected.
 */
export async function exportToFramework(model: DiagramModel, framework: Framework): Promise<FrameworkExport> {
    const g = await generatePython(model);
    switch (framework) {
        case 'xstate':
            return exportXState(model);
        case 'langgraph':
            return { fileName: `${g.moduleName.replace(/_fsm$/, '')}_langgraph.py`, code: langGraph(g), requires: [`${g.moduleName}.py`] };
        case 'burr':
            return { fileName: `${g.moduleName.replace(/_fsm$/, '')}_burr.py`, code: burr(g), requires: [`${g.moduleName}.py`] };
        case 'temporal':
            return { fileName: `${g.moduleName.replace(/_fsm$/, '')}_temporal.py`, code: temporal(model, g), requires: [`${g.moduleName}.py`] };
    }
}

const DECIDE_DOC = `Decide which event to fire in \`state\`: call your LLM, tool or a human here.

    allowed: the events the verified model allows now (offer them to the LLM, e.g. as a tool enum).
    values: attribute and variable values of the current state.
    Returning an event outside \`allowed\` raises InvalidTransition.`;

function header(g: GeneratedPython, framework: string): string {
    return `"""${g.className.replace(/FSM$/, '')} on ${framework}, generated by nuxmv-editor-js.

The control flow is the verified state machine of ${g.moduleName}.py (generate it from the same
diagram): each state only decides which event to fire, and the move is applied by the verified
machine, which rejects anything the model does not allow.
"""`;
}

function langGraph(g: GeneratedPython): string {
    return `${header(g, 'LangGraph')}

from typing import Any, Callable, TypedDict

from langgraph.graph import END, START, StateGraph

import ${g.moduleName} as m


class GraphState(TypedDict, total=False):
    fsm_state: str
    event: Any
    variables: dict
    history: list
    data: dict  # your agent's working memory


def decide(state: str, allowed: list, values: dict) -> str:
    """${DECIDE_DOC}"""
    raise NotImplementedError("decide(%r, %r): plug in your LLM / tool / human" % (state, allowed))


def _node(name: str, decide: Callable[[str, list, dict], str]):
    def node(state: GraphState) -> dict:
        fsm = m.${g.className}.restore(name, state.get("variables"), strict=False)
        allowed = [e.value for e in fsm.allowed_events()]
        if not allowed:  # final state: stop the graph
            return {"fsm_state": name, "event": None}
        event = decide(name, allowed, fsm.values)
        fsm.send(event)  # InvalidTransition if the choice is not a verified move
        return {
            "fsm_state": fsm.state.value,
            "event": event,
            "variables": dict(fsm.variables),
            "history": list(state.get("history", [])) + [event],
        }

    return node


def _route(state: GraphState):
    return END if state.get("event") is None else state["fsm_state"]


def build_graph(decide: Callable[[str, list, dict], str] = decide):
    """The LangGraph of the verified machine; compile() is already called."""
    graph = StateGraph(GraphState)
    for s in m.State:
        graph.add_node(s.value, _node(s.value, decide))
    graph.add_edge(START, m.INITIAL_STATES[0].value)
    for s in m.State:
        targets = sorted({t.value for (src, _), t in m.TRANSITIONS.items() if src == s})
        graph.add_conditional_edges(s.value, _route, targets + [END])
    return graph.compile()


def initial_state() -> GraphState:
    return {"fsm_state": m.INITIAL_STATES[0].value, "event": "", "variables": dict(m.VARIABLES), "history": [], "data": {}}


if __name__ == "__main__":
    app = build_graph()
    print(app.get_graph().draw_mermaid())
`;
}

function burr(g: GeneratedPython): string {
    return `${header(g, 'Burr')}

from typing import Callable

from burr.core import ApplicationBuilder, State, when
from burr.core.action import action

import ${g.moduleName} as m


def decide(state: str, allowed: list, values: dict) -> str:
    """${DECIDE_DOC}"""
    raise NotImplementedError("decide(%r, %r): plug in your LLM / tool / human" % (state, allowed))


def _action(name: str, decide: Callable[[str, list, dict], str]):
    @action(reads=["variables"], writes=["fsm_state", "variables", "event", "history"])
    def step(state: State) -> State:
        fsm = m.${g.className}.restore(name, state["variables"], strict=False)
        allowed = [e.value for e in fsm.allowed_events()]
        if not allowed:
            return state.update(fsm_state=name, event=None)
        event = decide(name, allowed, fsm.values)
        fsm.send(event)  # InvalidTransition if the choice is not a verified move
        return state.update(fsm_state=fsm.state.value, variables=dict(fsm.variables), event=event,
                            history=list(state.get("history", [])) + [event])

    return step


#: States where the run stops (no outgoing transition in the model).
FINAL_STATES = [s.value for s in m.TERMINAL_STATES]


def build_application(decide: Callable[[str, list, dict], str] = decide, **builder_options):
    builder = (
        ApplicationBuilder()
        .with_actions(**{s.value: _action(s.value, decide) for s in m.State})
        .with_transitions(*[(src.value, dst.value, when(event=ev.value)) for (src, ev), dst in m.TRANSITIONS.items()])
        .with_state(fsm_state=m.INITIAL_STATES[0].value, variables=dict(m.VARIABLES), event=None, history=[])
        .with_entrypoint(m.INITIAL_STATES[0].value)
    )
    for key, value in builder_options.items():
        builder = getattr(builder, key)(*value) if isinstance(value, tuple) else getattr(builder, key)(value)
    return builder.build()


if __name__ == "__main__":
    app = build_application()
    print(app.graph)
`;
}

function temporal(model: DiagramModel, g: GeneratedPython): string {
    const human = model.states
        .filter(s => /human|approv|admin|instructor|review/i.test(`${s.name} ${s.label ?? ''}`) || Object.values(s.values).includes('human'))
        .map(s => s.name);
    return `${header(g, 'Temporal')}

from datetime import timedelta

from temporalio import activity, workflow

with workflow.unsafe.imports_passed_through():
    import ${g.moduleName} as m

#: States decided by a person through the human_event signal instead of the decide activity.
#: Guessed from the diagram (names, labels, attributes mentioning a human): adjust as needed.
HUMAN_STATES = ${JSON.stringify(human)}


@activity.defn
async def decide(state: str, allowed: list, values: dict) -> str:
    """${DECIDE_DOC}

    Activities may call LLMs and other non-deterministic services; the workflow stays deterministic."""
    raise NotImplementedError("decide(%r, %r): plug in your LLM / tool" % (state, allowed))


@workflow.defn
class ${g.className.replace(/FSM$/, '')}Workflow:
    def __init__(self) -> None:
        self._human_events: list = []
        self._fsm = None

    @workflow.signal
    def human_event(self, event: str) -> None:
        """A person's decision (e.g. approve / reject) for the current human state."""
        self._human_events.append(event)

    @workflow.query
    def current_state(self) -> str:
        return self._fsm.state.value if self._fsm else m.INITIAL_STATES[0].value

    @workflow.query
    def allowed_events(self) -> list:
        return [e.value for e in self._fsm.allowed_events()] if self._fsm else []

    @workflow.run
    async def run(self, max_steps: int = 1000) -> list:
        # Workflows are single-threaded and sandboxed: no lock around send().
        fsm = m.${g.className}(on_invalid="return", thread_safe=False)
        self._fsm = fsm
        for _ in range(max_steps):
            allowed = [e.value for e in fsm.allowed_events()]
            if not allowed:
                break
            if fsm.state.value in HUMAN_STATES:
                await workflow.wait_condition(lambda: bool(self._human_events))
                event = self._human_events.pop(0)
            else:
                event = await workflow.execute_activity(
                    decide, args=[fsm.state.value, allowed, fsm.values], start_to_close_timeout=timedelta(minutes=5)
                )
            fsm.send(event)  # rejected choices leave the state unchanged: decide again
        return [record["event"] for record in fsm.history]
`;
}

// ---------------------------------------------------------------------------
// XState
// ---------------------------------------------------------------------------

async function exportXState(model: DiagramModel): Promise<FrameworkExport> {
    const parsed = await parseDiagram(serializeDiagram(model));
    const nodes = parsed.ast.elements.filter(e => e.$type === 'Transition');
    const names = new Set([...model.attributes.map(a => a.name), ...model.variables.map(v => v.name)]);
    const events = transitionEvents(model);
    const guards: string[] = [];
    const actions: string[] = [];
    const states = new Map<string, string[]>(model.states.map(s => [s.name, []]));
    const ranges = new Map(model.variables.filter(v => v.type.kind === 'range').map(v => [v.name, v.type as { low: number; high: number }]));

    model.transitions.forEach((t, i) => {
        const event = events[i];
        if (!event) return;
        const node = nodes[i];
        const parts: string[] = [];
        if (node?.$type === 'Transition' && node.guard) parts.push(js(node.guard, names));
        const updates = node?.$type === 'Transition' ? node.updates : [];
        for (const u of updates) {
            const r = ranges.get(u.variable.ref?.name ?? u.variable.$refText);
            if (r) parts.push(`inRange(${js(u.value, names)}, ${r.low}, ${r.high})`);
        }
        const entry = [`target: ${JSON.stringify(t.target)}`];
        if (parts.length > 0) {
            guards.push(`        g${i}: ({ context }) => { const v = values(${JSON.stringify(t.source)}, context); return ${parts.join(' && ')}; },`);
            entry.push(`guard: 'g${i}'`);
        }
        if (updates.length > 0) {
            const body = updates.map(u => `${u.variable.ref?.name ?? u.variable.$refText}: ${js(u.value, names)}`).join(', ');
            actions.push(`        u${i}: assign(({ context }) => { const v = values(${JSON.stringify(t.source)}, context); return { ${body} }; }),`);
            entry.push(`actions: 'u${i}'`);
        }
        states.get(t.source)!.push(`${JSON.stringify(event)}: { ${entry.join(', ')} }`);
    });

    const initial = (model.states.find(s => s.initial) ?? model.states[0]).name;
    const labels = Object.fromEntries(model.states.map(s => [s.name, Object.fromEntries(model.attributes.map(a => [a.name, s.values[a.name] === undefined ? null : jsValue(s.values[a.name], a.type.kind)]))]));
    const context = Object.fromEntries(model.variables.map(v => [v.name, jsValue(v.initial, v.type.kind)]));
    const eventUnion = [...new Set(events.filter(Boolean))].map(e => `{ type: ${JSON.stringify(e)} }`).join(' | ') || 'never';
    const contextType = model.variables.map(v => `${v.name}: ${v.type.kind === 'boolean' ? 'boolean' : v.type.kind === 'range' ? 'number' : 'string'}`).join('; ');

    const code = `/**
 * ${model.name ?? 'main'}: XState v5 machine generated by nuxmv-editor-js from the verified diagram.
 * Guards include the range checks of the updates, as in the nuXmv model.${model.states.filter(s => s.initial).length > 1 ? '\n * The diagram has several initial states; XState starts in the first one.' : ''}
 * Paste it into Stately (stately.ai/viz) to visualise it, or run it with createActor(machine).start().
 */
import { assign, setup } from 'xstate';

/** Labelling L(s): attribute values in each state (null = any value). */
export const LABELS: Record<string, Record<string, boolean | number | string | null>> = ${JSON.stringify(labels, null, 4)};

type Context = { ${contextType} };

const values = (state: string, context: Context): Record<string, unknown> => ({ ...LABELS[state], ...context, state });
const inRange = (x: number, low: number, high: number): boolean => x >= low && x <= high;

export const machine = setup({
    types: {
        context: {} as Context,
        events: {} as ${eventUnion}
    },
    guards: {
${guards.join('\n')}
    },
    actions: {
${actions.join('\n')}
    }
}).createMachine({
    id: ${JSON.stringify(model.name ?? 'main')},
    initial: ${JSON.stringify(initial)},
    context: ${JSON.stringify(context)},
    states: {
${model.states
    .map(s => {
        const on = states.get(s.name)!;
        return `        ${JSON.stringify(s.name)}: ${on.length === 0 ? "{ type: 'final' }" : `{\n            on: {\n                ${on.join(',\n                ')}\n            }\n        }`}`;
    })
    .join(',\n')}
    }
});
`;
    return { fileName: `${snakeName(model)}.machine.ts`, code, requires: [] };
}

function snakeName(model: DiagramModel): string {
    return (model.name ?? 'main').replace(/([a-z0-9])([A-Z])/g, '$1_$2').replace(/[^A-Za-z0-9]+/g, '_').toLowerCase();
}

function jsValue(value: string, kind: string): boolean | number | string {
    if (kind === 'boolean') return value === 'TRUE';
    if (kind === 'range') return Number(value);
    return value;
}

/** JavaScript for a present-time expression; names are looked up in v. */
function js(e: Expression, names: Set<string>): string {
    if (isBooleanLiteral(e)) return e.value === 'TRUE' ? 'true' : 'false';
    if (isNumberLiteral(e)) return String(e.value);
    if (isStateVariable(e)) return 'v.state';
    if (isNameReference(e)) return names.has(e.name) ? `(v[${JSON.stringify(e.name)}] as any)` : JSON.stringify(e.name);
    if (isUnaryExpression(e)) {
        if (e.operator === '!') return `!(${js(e.operand, names)})`;
        if (e.operator === '-') return `-(${js(e.operand, names)})`;
        throw new Error(`Temporal operator ${e.operator} in a guard or update.`);
    }
    if (isBinaryExpression(e)) {
        const a = js(e.left, names);
        const b = js(e.right, names);
        switch (e.operator) {
            case '&':
                return `(${a} && ${b})`;
            case '|':
                return `(${a} || ${b})`;
            case '->':
                return `(!(${a}) || ${b})`;
            case '<->':
            case 'xnor':
                return `(${a} === ${b})`;
            case 'xor':
                return `(${a} !== ${b})`;
            case '=':
                return `(${a} === ${b})`;
            case '!=':
                return `(${a} !== ${b})`;
            case '/':
                return `Math.trunc(${a} / ${b})`;
            case 'mod':
                return `(${a} % ${b})`;
            case 'U':
            case 'V':
            case 'S':
            case 'T':
                throw new Error(`Temporal operator ${e.operator} in a guard or update.`);
            default:
                return `(${a} ${e.operator} ${b})`;
        }
    }
    throw new Error('Unsupported expression in a guard or update.');
}
