import { hasData, type DiagramModel } from './model.js';
import { Semantics, type Configuration } from './semantics.js';
import { generatePython, type GeneratedPython, type PythonTransition } from './python-generator.js';

export interface NotebookOptions {
    sourceName?: string;
    /** Verdicts from the last nuXmv run, one per specification ('true' | 'false' | 'unknown'). */
    verdicts?: Array<string | undefined>;
    /** Counterexamples to replay: the sequence of states of each nuXmv trace. */
    counterexamples?: Array<{ property: string; states: string[]; loopStart?: number }>;
    /** Editor URL for the live link cell. */
    editorUrl?: string;
}

interface Cell {
    cell_type: 'markdown' | 'code';
    id: string;
    metadata: Record<string, unknown>;
    source: string[];
    outputs?: unknown[];
    execution_count?: null;
}

/**
 * Builds a Jupyter notebook showcasing the generated Python implementation:
 * the module, its live diagram, a walk through the model, enforcement of the
 * verified transitions, replays of nuXmv counterexamples and the editor link.
 */
export async function generateNotebook(model: DiagramModel, options: NotebookOptions = {}): Promise<{ notebook: string; python: GeneratedPython }> {
    const g = await generatePython(model, { sourceName: options.sourceName });
    const cells: Cell[] = [];
    let n = 0;
    const md = (text: string) => cells.push({ cell_type: 'markdown', id: `cell-${++n}`, metadata: {}, source: lines(text) });
    const code = (text: string) => cells.push({ cell_type: 'code', id: `cell-${++n}`, metadata: {}, source: lines(text), outputs: [], execution_count: null });
    const name = model.name ?? 'main';

    md(
        `# ${name}: verified state machine in Python\n\n` +
            `Generated by [nuxmv-editor-js](https://github.com/belkassaby/nuxmv-editor-js)${options.sourceName ? ` from \`${options.sourceName}\`` : ''}. ` +
            `The diagram was model checked with nuXmv; this notebook runs the **same** transition system as Python code:\n\n` +
            `* \`send(event)\` only follows transitions of the verified model, anything else raises \`InvalidTransition\`;\n` +
            `* \`allowed_events()\` gives the legal next steps, e.g. to constrain what an LLM may choose;\n` +
            `* runtime monitors re-check the properties that can be decided on a running system.\n\n` +
            propertyTable(g, options.verdicts)
    );
    code('# The live diagram widget needs anywidget (the rest has no dependency).\n%pip install --quiet anywidget');
    code(`%%writefile ${g.moduleName}.py\n${g.code}`);
    code(
        `import importlib, time\n` +
            `import ${g.moduleName} as m\n` +
            `importlib.reload(m)\n\n` +
            `fsm = m.${g.className}()\n` +
            `fsm  # rendered as a diagram with the current state highlighted`
    );
    md('## Live diagram\n\nThe widget below follows the state of `fsm`: run the next cells and watch it move (current state in orange, possible next states dotted green).');
    code('try:\n    live = fsm.widget(height=460)\nexcept ImportError as error:\n    live = None\n    print(error)\nlive');

    const sem = hasData(model) ? await Semantics.of(model) : null;
    const path = sem ? demoPathWithData(model, g, sem) : demoPath(model, g.transitions);
    md(
        `## Walking through the model\n\n` +
            (path.reaches ? `A shortest path from the initial state to the final state \`${path.reaches}\`.` : 'A walk through the model, visiting new states first.') +
            ' Each `send` is checked against the verified transition table.'
    );
    code(
        `path = ${pyList(path.events)}\n\n` +
            `for event in path:\n` +
            `    fsm.send(event)\n` +
            `    print(f"{event:>30}  ->  {fsm.state.value}")\n` +
            `    time.sleep(0.4)  # let the live diagram animate`
    );
    code('fsm  # the diagram again, with the visited states');

    const illegal = g.transitions.map(t => t.event).find(e => !g.transitions.some(t => t.source === initialOf(model) && t.event === e));
    md('## The verified model is enforced\n\nAn event that has no transition from the current state is rejected, whatever produced it: an LLM, a tool or a person.');
    code(
        `fresh = m.${g.className}()\n` +
            `print("allowed:", [e.value for e in fresh.allowed_events()])\n` +
            `try:\n` +
            `    fresh.send(${illegal ? `"${illegal}"` : '"NOT_AN_EVENT"'})\n` +
            `except m.InvalidTransition as error:\n` +
            `    print("rejected:", error)`
    );

    md(
        '## Constraining an LLM to legal moves\n\n' +
            'Instead of letting the model decide freely, offer it only the events allowed in the current state, ' +
            'for example as the `enum` of a tool parameter. Whatever it answers, `send` still validates it.'
    );
    code(
        `def next_step_tool(fsm):\n` +
            `    """Tool definition whose only valid arguments are the legal next events."""\n` +
            `    return {\n` +
            `        "name": "next_step",\n` +
            `        "description": f"Choose the next step. Current state: {fsm.state.value}.",\n` +
            `        "input_schema": {\n` +
            `            "type": "object",\n` +
            `            "properties": {"event": {"type": "string", "enum": [e.value for e in fsm.allowed_events()]}},\n` +
            `            "required": ["event"],\n` +
            `        },\n` +
            `    }\n\n` +
            `next_step_tool(m.${g.className}())`
    );

    md(
        '## Attaching work to states\n\n' +
            'Subclass the machine and define `on_enter_<state>` (or `on_exit_<state>`) hooks: this is where LLM calls, tools and ' +
            'human approvals go. The control flow itself stays the verified one.'
    );
    const first = path.states[1] ?? model.states[0].name;
    code(
        `class My${g.className}(m.${g.className}):\n` +
            `    def on_enter_${first}(self, event, data):\n` +
            `        print(f"entered ${first} via {event.value}; call your agent or tool here")\n\n` +
            `agent = My${g.className}()\n` +
            `agent.send(${pyStr(path.events[0] ?? '')})` +
            (path.events.length === 0 ? '  # no transition from the initial state' : '')
    );

    const replays = (options.counterexamples ?? [])
        .map(c => ({ ...c, events: sem ? eventsWithData(c.states, g, sem) : eventsFor(c.states, g.transitions) }))
        .filter(c => c.events !== null);
    if (replays.length > 0) {
        md(
            '## Replaying nuXmv counterexamples\n\n' +
                'Each false property came with a counterexample. Replaying it on the implementation shows the scenario the design allows; ' +
                'lasso-shaped traces are replayed once around their loop.'
        );
        for (const r of replays) {
            code(
                `# ${r.property}\n` +
                    `cex = m.${g.className}(strict=False)\n` +
                    `for event in ${pyList(r.events ?? [])}:\n` +
                    `    cex.send(event)\n` +
                    `    time.sleep(0.2)\n` +
                    `cex`
            );
        }
    }

    md(
        '## Runtime monitors\n\nMonitored properties are re-checked after every transition; in strict mode (the default) a violation raises `PropertyViolation`.'
    );
    code('for monitor in fsm.monitors:\n    status = "ok" if monitor.violated_at is None else f"violated at step {monitor.violated_at}"\n    print(f"{monitor.kind:10} {monitor.name:30} {status}")');

    md(
        '## Live state in nuxmv-editor\n\n' +
            'The same states can be shown in the editor while any Python process runs: open the **Trace** tab, choose ' +
            '**Live from Python**, pick a channel, then link the machine to it.'
    );
    code(`# fsm.link_editor(${pyStr(options.editorUrl ?? 'http://127.0.0.1:3000')}, channel="notebook")\n# fsm.send(...)  # every transition now also moves the editor's diagram`);

    const notebook = {
        cells,
        metadata: {
            kernelspec: { display_name: 'Python 3', language: 'python', name: 'python3' },
            language_info: { name: 'python' },
            nuxmv_editor: { diagram: name, generator: 'nuxmv-editor-js' }
        },
        nbformat: 4,
        nbformat_minor: 5
    };
    return { notebook: JSON.stringify(notebook, null, 1) + '\n', python: g };
}

function propertyTable(g: GeneratedPython, verdicts?: Array<string | undefined>): string {
    if (g.monitors.length === 0) return '_The diagram has no properties yet._';
    const rows = g.monitors.map((m, i) => {
        const verdict = verdicts?.[i];
        const v = verdict === 'true' ? '✓ holds' : verdict === 'false' ? '✗ false' : verdict === 'unknown' ? '? unknown' : '—';
        return `| ${m.kind} | \`${m.name}\` | \`${m.expression.replace(/\|/g, '\\|')}\` | ${v} | ${m.monitored ? 'yes' : `no (${m.reason})`} |`;
    });
    return ['| Kind | Name | Property | nuXmv | Monitored at run time |', '| --- | --- | --- | --- | --- |', ...rows].join('\n');
}

function initialOf(model: DiagramModel): string {
    return (model.states.find(s => s.initial) ?? model.states[0]).name;
}

/** Shortest path to a final state if there is one, else a walk preferring unvisited states. */
function demoPath(model: DiagramModel, transitions: PythonTransition[]): { events: string[]; states: string[]; reaches?: string } {
    const start = initialOf(model);
    const out = new Map<string, PythonTransition[]>();
    for (const t of transitions) out.set(t.source, [...(out.get(t.source) ?? []), t]);
    const finals = new Set(model.states.map(s => s.name).filter(s => !(out.get(s) ?? []).some(t => t.target !== s)));

    const prev = new Map<string, PythonTransition | null>([[start, null]]);
    const queue = [start];
    while (queue.length > 0) {
        const s = queue.shift()!;
        if (finals.has(s) && s !== start) {
            const path: PythonTransition[] = [];
            for (let t = prev.get(s); t; t = prev.get(t.source)) path.unshift(t);
            return { events: path.map(t => t.event), states: [start, ...path.map(t => t.target)], reaches: s };
        }
        for (const t of out.get(s) ?? []) {
            if (!prev.has(t.target)) {
                prev.set(t.target, t);
                queue.push(t.target);
            }
        }
    }
    const events: string[] = [];
    const states = [start];
    const seen = new Set([start]);
    let current = start;
    for (let i = 0; i < 10; i++) {
        const options = out.get(current) ?? [];
        const next = options.find(t => !seen.has(t.target)) ?? options[0];
        if (!next) break;
        events.push(next.event);
        states.push(next.target);
        seen.add(next.target);
        current = next.target;
    }
    return { events, states };
}

/** Events that take the runtime through a nuXmv trace (null if a step has no transition). */
// nuXmv lasso traces already end in a copy of the state where the loop starts,
// so replaying the states in order goes once around the loop.
function eventsFor(states: string[], transitions: PythonTransition[]): string[] | null {
    const seq = states;
    const events: string[] = [];
    for (let i = 1; i < seq.length; i++) {
        if (seq[i] === seq[i - 1] && !transitions.some(t => t.source === seq[i] && t.target === seq[i])) continue; // stutter
        const t = transitions.find(x => x.source === seq[i - 1] && x.target === seq[i]);
        if (!t) return null;
        events.push(t.event);
    }
    return events;
}

function lines(text: string): string[] {
    const parts = text.split('\n');
    return parts.map((l, i) => (i < parts.length - 1 ? l + '\n' : l));
}

function pyStr(s: string): string {
    return JSON.stringify(s);
}

function pyList(items: string[]): string {
    if (items.length <= 4) return `[${items.map(pyStr).join(', ')}]`;
    return '[\n' + items.map(i => `    ${pyStr(i)},`).join('\n') + '\n]';
}

/** Like demoPath, over configurations (state + variables) so that guards are respected. */
function demoPathWithData(model: DiagramModel, g: GeneratedPython, sem: Semantics): { events: string[]; states: string[]; reaches?: string } {
    const eventOf = new Map(g.transitions.map(t => [t.index, t.event]));
    const finals = new Set(g.terminalStates);
    const start = sem.initialConfigurations()[0];
    const key = (c: { state: string; variables: object }) => JSON.stringify(c);
    const prev = new Map<string, { from: string; event: string; state: string } | null>([[key(start), null]]);
    const queue = [start];
    while (queue.length > 0 && prev.size < 20000) {
        const c = queue.shift()!;
        const k = key(c);
        if (finals.has(c.state) && c.state !== start.state) {
            const events: string[] = [];
            const states: string[] = [];
            for (let p = prev.get(k); p; p = prev.get(p.from)) {
                events.unshift(p.event);
                states.unshift(p.state);
            }
            return { events, states: [start.state, ...states], reaches: c.state };
        }
        for (const s of sem.successors(c)) {
            if (s.transition === null) continue;
            const event = eventOf.get(s.transition);
            const nk = key(s.config);
            if (!event || prev.has(nk)) continue;
            prev.set(nk, { from: k, event, state: s.config.state });
            queue.push(s.config);
        }
    }
    return demoPath(model, g.transitions);
}

function eventsWithData(states: string[], g: GeneratedPython, sem: Semantics): string[] | null {
    const eventOf = new Map(g.transitions.map(t => [t.index, t.event]));
    const start = sem.initialConfigurations().find(c => c.state === states[0]);
    if (!start) return null;
    let config: Configuration = start;
    const events: string[] = [];
    for (let i = 1; i < states.length; i++) {
        const step: { transition: number | null; config: Configuration } | undefined = sem.successors(config).find(s => s.config.state === states[i]);
        if (!step) return null;
        if (step.transition !== null) {
            const event = eventOf.get(step.transition);
            if (!event) return null;
            events.push(event);
        }
        config = step.config;
    }
    return events;
}
