import type { DiagramModel } from './model.js';
import { replayEvents, walkThrough } from './notebook-generator.js';
import { generatePython } from './python-generator.js';

export interface PytestOptions {
    sourceName?: string;
    /** nuXmv counterexamples (state sequences) to replay as regression scenarios. */
    counterexamples?: Array<{ property: string; states: string[] }>;
    /** Event sequences to replay (e.g. from the notebook generator's walk-through). */
    scenarios?: Array<{ name: string; events: string[] }>;
}

/**
 * Generates a pytest module with Hypothesis stateful tests for the generated
 * state machine: random sequences of allowed events must follow the verified
 * table and keep the monitored properties, illegal events must be rejected,
 * and counterexample scenarios are replayed. Point FSM at a subclass to test
 * your own hooks and glue code against the model.
 */
export async function generatePythonTests(model: DiagramModel, options: PytestOptions = {}): Promise<{ fileName: string; code: string }> {
    const g = await generatePython(model, { sourceName: options.sourceName });
    const name = g.className.replace(/FSM$/, '');
    const lines: string[] = [];
    lines.push(`"""Property-based tests for ${g.className}, generated by ProvenFlow${options.sourceName ? ` from ${options.sourceName}` : ''}.`);
    lines.push('');
    lines.push(`Run: pip install pytest hypothesis && pytest test_${g.moduleName}.py`);
    lines.push('"""');
    lines.push('');
    lines.push('import pytest');
    lines.push('from hypothesis import settings');
    lines.push('from hypothesis import strategies as st');
    lines.push('from hypothesis.stateful import RuleBasedStateMachine, invariant, rule');
    lines.push('');
    lines.push(`import ${g.moduleName} as m`);
    lines.push('');
    lines.push('#: The machine under test: replace with your subclass (with on_enter_ hooks) to test it against the model.');
    lines.push(`FSM = m.${g.className}`);
    lines.push('');
    lines.push('');
    lines.push(`class ${name}Model(RuleBasedStateMachine):`);
    lines.push('    """Random runs: every step must follow the verified transition table."""');
    lines.push('');
    lines.push('    def __init__(self):');
    lines.push('        super().__init__()');
    lines.push('        self.fsm = FSM()');
    lines.push('');
    lines.push('    @rule(data=st.data())');
    lines.push('    def fire_an_allowed_event(self, data):');
    lines.push('        allowed = self.fsm.allowed_events()');
    lines.push('        if not allowed:');
    lines.push('            return');
    lines.push('        event = data.draw(st.sampled_from(allowed))');
    lines.push('        before = self.fsm.state');
    lines.push('        self.fsm.send(event)');
    lines.push('        assert self.fsm.state == m.TRANSITIONS[(before, event)]');
    lines.push('');
    lines.push('    @rule(event=st.sampled_from(list(m.Event)) if list(m.Event) else st.nothing())');
    lines.push('    def illegal_events_are_rejected(self, event):');
    lines.push('        if self.fsm.can(event):');
    lines.push('            return');
    lines.push('        before, variables = self.fsm.state, dict(self.fsm.variables)');
    lines.push('        policy, self.fsm.on_invalid = self.fsm.on_invalid, "raise"');
    lines.push('        try:');
    lines.push('            with pytest.raises(m.InvalidTransition):');
    lines.push('                self.fsm.send(event)');
    lines.push('        finally:');
    lines.push('            self.fsm.on_invalid = policy');
    lines.push('        assert self.fsm.state == before and self.fsm.variables == variables');
    lines.push('');
    lines.push('    @invariant()');
    lines.push('    def monitored_properties_hold(self):');
    lines.push('        broken = [f"{x.kind} {x.name}: {x.formula}" for x in self.fsm.monitors if x.violated_at is not None]');
    lines.push('        assert not broken, broken');
    lines.push('');
    lines.push('    @invariant()');
    lines.push('    def values_stay_in_their_domains(self):');
    lines.push('        for name, value in self.fsm.values.items():');
    lines.push('            if name != "state" and value is not None:');
    lines.push('                assert value in m.DOMAINS[name], (name, value)');
    lines.push('');
    lines.push('');
    lines.push(`Test${name}Model = ${name}Model.TestCase`);
    lines.push(`Test${name}Model.settings = settings(max_examples=100, stateful_step_count=40, deadline=None)`);
    lines.push('');

    const walk = await walkThrough(model, g);
    const scenarios = [...(walk.events.length > 0 ? [{ name: walk.reaches ? `walk to ${walk.reaches}` : 'walk-through', events: walk.events }] : []), ...(options.scenarios ?? [])];
    const replays: Array<{ property: string; events: string[] }> = [];
    for (const c of options.counterexamples ?? []) {
        const events = await replayEvents(model, g, c.states);
        if (events) replays.push({ property: c.property, events });
    }
    if (scenarios.length > 0 || replays.length > 0) {
        lines.push('');
        lines.push('# Scenarios: the walk-through and the counterexamples found by nuXmv. A counterexample shows');
        lines.push('# behaviour the design allows although a property says it should not: keep it as a regression');
        lines.push('# test of the implementation, or fix the design and regenerate.');
        lines.push('SCENARIOS = [');
        for (const s of scenarios) lines.push(`    (${JSON.stringify(s.name)}, ${JSON.stringify(s.events)}),`);
        for (const r of replays) lines.push(`    (${JSON.stringify(`counterexample: ${r.property}`)}, ${JSON.stringify(r.events)}),`);
        lines.push(']');
        lines.push('');
        lines.push('');
        lines.push('@pytest.mark.parametrize("name, events", SCENARIOS, ids=[s[0] for s in SCENARIOS])');
        lines.push('def test_scenario_is_executable(name, events):');
        lines.push('    fsm = FSM(strict=False)');
        lines.push('    for event in events:');
        lines.push('        assert fsm.can(event), f"{event} not allowed in {fsm.state.value}"');
        lines.push('        fsm.send(event)');
    }
    lines.push('');
    return { fileName: `test_${g.moduleName}.py`, code: lines.join('\n') };
}
