import { attributeDomain, deadEndStates, hasData, successors, type DiagramModel, type TransitionDef } from './model.js';

export interface GeneratedModel {
    /** The nuXmv input file. */
    text: string;
    /** Non fatal remarks produced while generating (dead ends, defaults...). */
    notes: string[];
}

export class GenerationError extends Error {}

/**
 * Generates a "sequential style" nuXmv model from a diagram, following the
 * algorithm of the original NusmvFileWriter (VAR / ASSIGN / specifications)
 * while lifting its limitations:
 *
 *  - several initial states are supported (`init(state) := {s0, s2}`);
 *  - dead-end states no longer produce `state = s0 : {};` syntax errors,
 *    they stutter (loop on themselves) so that every path is infinite;
 *  - states without a value for an attribute leave it unconstrained;
 *  - FAIRNESS/JUSTICE constraints and LTL, CTL and invariant specifications.
 */
export function generateSmv(model: DiagramModel): GeneratedModel {
    if (model.states.length === 0) {
        throw new GenerationError('The diagram has no states: draw at least one state before generating the nuXmv model.');
    }
    const notes: string[] = [];
    const lines: string[] = [];
    const states = model.states.map(s => s.name);
    const indent = '    ';

    lines.push(`-- nuXmv model generated by ProvenFlow from diagram '${model.name ?? 'main'}'`);
    lines.push(`-- ${states.length} state(s), ${model.transitions.length} transition(s), ${model.attributes.length} attribute(s)`);
    lines.push('MODULE main');

    // ----- VAR ------------------------------------------------------------
    lines.push('VAR');
    lines.push(`${indent}state : {${states.join(', ')}};`);
    for (const attribute of [...model.attributes, ...model.variables]) {
        const type = attribute.type;
        const decl = type.kind === 'boolean' ? 'boolean' : type.kind === 'range' ? `${type.low}..${type.high}` : `{${type.values.join(', ')}}`;
        lines.push(`${indent}${attribute.name} : ${decl};`);
    }
    const data = hasData(model);

    // ----- ASSIGN: initial states and transition relation -------------------
    lines.push('ASSIGN');
    lines.push(`${indent}-- initial state(s) and transition relation`);
    let initials = model.states.filter(s => s.initial).map(s => s.name);
    if (initials.length === 0) {
        initials = [states[0]];
        notes.push(`No initial state declared, using '${states[0]}'.`);
    }
    lines.push(`${indent}init(state) := ${setOrValue(initials)};`);
    for (const v of model.variables) lines.push(`${indent}init(${v.name}) := ${v.initial};`);

    const deadEnds = new Set(deadEndStates(model));
    if (data) {
        // Guards and updates: the transition relation is given below as TRANS.
        if (deadEnds.size > 0) notes.push(`Dead-end state(s) ${[...deadEnds].join(', ')} loop on themselves.`);
    } else {
    lines.push(`${indent}next(state) := case`);
    for (const state of states) {
        if (deadEnds.has(state)) {
            lines.push(`${indent}${indent}state = ${state} : ${state}; -- dead end: stutter`);
        } else {
            lines.push(`${indent}${indent}state = ${state} : ${setOrValue(successors(model, state))};`);
        }
    }
    // Unreachable once every state is listed, but keeps nuXmv's exhaustiveness check quiet.
    lines.push(`${indent}${indent}TRUE : state;`);
    lines.push(`${indent}esac;`);
    if (deadEnds.size > 0) {
        notes.push(`Dead-end state(s) ${[...deadEnds].join(', ')} loop on themselves.`);
    }
    }

    // ----- ASSIGN: labelling function L(s) ----------------------------------
    if (model.attributes.length > 0) {
        lines.push(`${indent}-- labelling of the states`);
    }
    for (const attribute of model.attributes) {
        const domain = attributeDomain(attribute.type);
        const branches: string[] = [];
        let unassigned = 0;
        for (const state of model.states) {
            const value = state.values[attribute.name];
            if (value === undefined || value === '') {
                unassigned++;
                continue;
            }
            branches.push(`${indent}${indent}state = ${state.name} : ${value};`);
        }
        if (branches.length === 0) {
            // Unconstrained everywhere: leave the variable free.
            lines.push(`${indent}-- ${attribute.name} is not constrained by any state`);
            continue;
        }
        lines.push(`${indent}${attribute.name} := case`);
        lines.push(...branches);
        const any = attribute.type.kind === 'range' ? `${attribute.type.low}..${attribute.type.high}` : setOrValue(domain);
        lines.push(`${indent}${indent}TRUE : ${any};${unassigned > 0 ? '' : ' -- unreachable'}`);
        lines.push(`${indent}esac;`);
    }

    if (data) lines.push(...transRelation(model, indent));

    // ----- Fairness and specifications ---------------------------------------
    for (const f of model.fairness) {
        lines.push(`${f.kind}`, `${indent}${f.expression};`);
    }
    for (const s of model.specs) {
        lines.push(`${s.kind}${s.name ? ` NAME ${s.name} :=` : ''}`, `${indent}${s.expression};`);
    }

    return { text: lines.join('\n') + '\n', notes };
}

function setOrValue(values: string[]): string {
    return values.length === 1 ? values[0] : `{${values.join(', ')}}`;
}

/**
 * Transition relation with guards and updates. A transition is enabled when
 * the machine is in its source state, its guard holds and its updates stay in
 * the variables' ranges; variables it does not update keep their value. When
 * no transition is enabled the machine stutters, so every path is infinite.
 */
function transRelation(model: DiagramModel, indent: string): string[] {
    const ranges = new Map(model.variables.filter(v => v.type.kind === 'range').map(v => [v.name, v.type as { low: number; high: number }]));
    const enabled = (t: TransitionDef) => {
        const parts = [`state = ${t.source}`];
        if (t.guard) parts.push(`(${t.guard})`);
        for (const u of t.updates ?? []) {
            const r = ranges.get(u.variable);
            const constant = /^-?\d+$/.test(u.expression.trim()) ? Number(u.expression) : undefined;
            if (r && !(constant !== undefined && constant >= r.low && constant <= r.high)) {
                parts.push(`(${u.expression}) >= ${r.low} & (${u.expression}) <= ${r.high}`);
            }
        }
        return parts.join(' & ');
    };
    const lines = ['TRANS'];
    model.transitions.forEach((t, i) => {
        const next = [`next(state) = ${t.target}`];
        for (const v of model.variables) {
            const u = t.updates?.find(x => x.variable === v.name);
            next.push(`next(${v.name}) = ${u ? `(${u.expression})` : v.name}`);
        }
        lines.push(`${indent}${i === 0 ? '  ' : '| '}(${enabled(t)} & ${next.join(' & ')})${t.label ? ` -- ${t.label}` : ''}`);
    });
    const any = model.transitions.map(t => `(${enabled(t)})`).join(' | ') || 'FALSE';
    const stay = ['next(state) = state', ...model.variables.map(v => `next(${v.name}) = ${v.name}`)].join(' & ');
    lines.push(`${indent}${model.transitions.length === 0 ? '  ' : '| '}(!(${any}) & ${stay}) -- nothing enabled: stutter`);
    lines.push(`${indent};`);
    return lines;
}
