import { attributeDomain, deadEndStates, successors, type DiagramModel } from './model.js';

export interface GeneratedModel {
    /** The nuXmv input file. */
    text: string;
    /** Non fatal remarks produced while generating (dead ends, defaults...). */
    notes: string[];
}

export class GenerationError extends Error {}

/**
 * Generates a "sequential style" nuXmv model from a diagram, following the
 * algorithm of the original NusmvFileWriter (VAR / ASSIGN / specifications)
 * while lifting its limitations:
 *
 *  - several initial states are supported (`init(state) := {s0, s2}`);
 *  - dead-end states no longer produce `state = s0 : {};` syntax errors,
 *    they stutter (loop on themselves) so that every path is infinite;
 *  - states without a value for an attribute leave it unconstrained;
 *  - FAIRNESS/JUSTICE constraints and LTL, CTL and invariant specifications.
 */
export function generateSmv(model: DiagramModel): GeneratedModel {
    if (model.states.length === 0) {
        throw new GenerationError('The diagram has no states: draw at least one state before generating the nuXmv model.');
    }
    const notes: string[] = [];
    const lines: string[] = [];
    const states = model.states.map(s => s.name);
    const indent = '    ';

    lines.push(`-- nuXmv model generated by nuxmv-editor-js from diagram '${model.name ?? 'main'}'`);
    lines.push(`-- ${states.length} state(s), ${model.transitions.length} transition(s), ${model.attributes.length} attribute(s)`);
    lines.push('MODULE main');

    // ----- VAR ------------------------------------------------------------
    lines.push('VAR');
    lines.push(`${indent}state : {${states.join(', ')}};`);
    for (const attribute of model.attributes) {
        const type = attribute.type;
        const decl = type.kind === 'boolean' ? 'boolean' : type.kind === 'range' ? `${type.low}..${type.high}` : `{${type.values.join(', ')}}`;
        lines.push(`${indent}${attribute.name} : ${decl};`);
    }

    // ----- ASSIGN: initial states and transition relation -------------------
    lines.push('ASSIGN');
    lines.push(`${indent}-- initial state(s) and transition relation`);
    let initials = model.states.filter(s => s.initial).map(s => s.name);
    if (initials.length === 0) {
        initials = [states[0]];
        notes.push(`No initial state declared, using '${states[0]}'.`);
    }
    lines.push(`${indent}init(state) := ${setOrValue(initials)};`);

    const deadEnds = new Set(deadEndStates(model));
    lines.push(`${indent}next(state) := case`);
    for (const state of states) {
        if (deadEnds.has(state)) {
            lines.push(`${indent}${indent}state = ${state} : ${state}; -- dead end: stutter`);
        } else {
            lines.push(`${indent}${indent}state = ${state} : ${setOrValue(successors(model, state))};`);
        }
    }
    // Unreachable once every state is listed, but keeps nuXmv's exhaustiveness check quiet.
    lines.push(`${indent}${indent}TRUE : state;`);
    lines.push(`${indent}esac;`);
    if (deadEnds.size > 0) {
        notes.push(`Dead-end state(s) ${[...deadEnds].join(', ')} loop on themselves.`);
    }

    // ----- ASSIGN: labelling function L(s) ----------------------------------
    if (model.attributes.length > 0) {
        lines.push(`${indent}-- labelling of the states`);
    }
    for (const attribute of model.attributes) {
        const domain = attributeDomain(attribute.type);
        const branches: string[] = [];
        let unassigned = 0;
        for (const state of model.states) {
            const value = state.values[attribute.name];
            if (value === undefined || value === '') {
                unassigned++;
                continue;
            }
            branches.push(`${indent}${indent}state = ${state.name} : ${value};`);
        }
        if (branches.length === 0) {
            // Unconstrained everywhere: leave the variable free.
            lines.push(`${indent}-- ${attribute.name} is not constrained by any state`);
            continue;
        }
        lines.push(`${indent}${attribute.name} := case`);
        lines.push(...branches);
        const any = attribute.type.kind === 'range' ? `${attribute.type.low}..${attribute.type.high}` : setOrValue(domain);
        lines.push(`${indent}${indent}TRUE : ${any};${unassigned > 0 ? '' : ' -- unreachable'}`);
        lines.push(`${indent}esac;`);
    }

    // ----- Fairness and specifications ---------------------------------------
    for (const f of model.fairness) {
        lines.push(`${f.kind}`, `${indent}${f.expression};`);
    }
    for (const s of model.specs) {
        lines.push(`${s.kind}${s.name ? ` NAME ${s.name} :=` : ''}`, `${indent}${s.expression};`);
    }

    return { text: lines.join('\n') + '\n', notes };
}

function setOrValue(values: string[]): string {
    return values.length === 1 ? values[0] : `{${values.join(', ')}}`;
}
